name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  test-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yml
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
# vars.DOCKERHUB_USER and secrets.DOCKERHUB_TOKEN are value retrieved from Github action variable and secret settings
# DOCKERHUB_USER and DOCKERHUB_TOKEN are defined in "test-and-lint.yml" files 
