name: Deploy

on:
  push:
    branches:
      - main
      - prod

jobs:
  test-lint:
    uses: ./.github/workflows/test-and-lint.yml
    name: Test and Lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test-lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set workspace
        run: |
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            echo "prod" > .workspace
          else
            echo "staging" > .workspace
          fi

      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker images
        run: |
          docker build --compress -t ${{ secrets.ECR_REPO_APP }}:$GITHUB_SHA .
          docker push ${{ secrets.ECR_REPO_APP }}:$GITHUB_SHA

          docker build --compress -t ${{ secrets.ECR_REPO_PROXY }}:$GITHUB_SHA proxy/
          docker push ${{ secrets.ECR_REPO_PROXY }}:$GITHUB_SHA
